### PR TITLE
New release

### PR DESCRIPTION
**Pull request by ocefpaf**
@Conengmo I'll tag the release as soon as you review and merge this one.

### CODE REVIEW

**Comment by Conengmo** [comment]
Looks good, and good that you added to the changelog. As you can see Travis is failing, it's on these two lines:

**Comment by ocefpaf** [comment]
> Looks good, and good that you added to the changelog. As you can see Travis is failing, it's on these two lines:

I'm fixing those...

**Comment by ocefpaf** [comment]
@Conengmo are we dropping Python 2 in this release? If so I can send another PR before the release to remove it/

**Comment by Conengmo** [comment]
Almost forgot but we are indeed dropping Python 2 with branca 0.4.0. There already was a PR for that: https://github.com/python-visualization/branca/pull/56. This change updated `setup.py`. What else should we do?

**Comment by ocefpaf** [comment]
> Almost forgot but we are indeed dropping Python 2 with branca 0.4.0. There already was a PR for that: #56. This change updated `setup.py`. What else should we do?

Remove Python 2 code and workarounds. I'll send a PR soon.

**Comment by Conengmo** [comment]
Let's get this release out before that then, so we don't have to hurry.

**Comment by Conengmo** [comment]
Oh and maybe good to add the Python 2 dropping to the changelog

**Comment by ocefpaf** [comment]
> Let's get this release out before that then, so we don't have to hurry with reviewing and testing that.

Sure.

> Oh and maybe good to add the Python 2 dropping to the changelog

I'll added that in a sec...

**Comment by Conengmo** [comment]
This one is good to go it seems! 🚀 ?

**Comment by ocefpaf** [comment]
> This one is good to go it seems!  ?

I'm done, no more commits :-)

Feel free to merge if you are OK with the changes here.

**Comment by Conengmo** [comment]
Great, time to release!

**Pull request merged**
