### PR TITLE
Remove embedded IFrame's border

### PR DESCRIPTION
**Pull request by deelaka**
PR as per your [request](https://github.com/python-visualization/folium/issues/423#issuecomment-237967700) on fixing issue [#423](https://github.com/python-visualization/folium/issues/423) on folium. :smile:

### CODE REVIEW

**Comment by BibMartin** [comment]
Excellent ; thank you !

**Comment by BibMartin** [comment]
oups, you need to split the line for the pep8 test to pass.

**Comment by deelaka** [comment]
@BibMartin Fixed the pep8 issue, ready to merge! :smile:

**Comment by BibMartin** [comment]
Great ; it's a merge ! Thanks @deelaka

**Comment by ocefpaf** [comment]
Awesome @deelaka! Thanks for moving this forward!

**Comment by deelaka** [comment]
@ocefpaf sure thing! :smile:

**Comment by deelaka** [comment]
@ocefpaf @BibMartin The changes I've made should actually occur on Line [550-564](https://github.com/python-visualization/branca/blob/master/branca/element.py#L550-L564) in the `IFrame` class not in Line 318 area in the Figure class. I found this while generating some maps today. I'm sorry for the inconvenience caused its just that I did not double check the lines that ocepaf had [pointed ](https://github.com/python-visualization/folium/issues/423#issuecomment-237967700) me towards.

**Pull request merged**
