### PR TITLE
dash-separated key will no longer be supported

### PR DESCRIPTION
**Pull request by atupone**

### CODE REVIEW

**Comment by Conengmo** [comment]
Hi @atupone, can you clarify what package you are talking about, that will no longer support this dash-separated key?

**Comment by atupone** [comment]
Setuptools

Il ven 30 lug 2021, 22:06 Frank ***@***.***> ha scritto:

**Comment by martinfleis** [comment]
xref https://github.com/pypa/setuptools/pull/2588

**Comment by Conengmo** [comment]
It seems that setuptools does recognize the `description-file` syntax, though the table says they themselves use a different syntax: https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html#compatibility-with-other-tools. I don't see `description_file` anywhere here, so I'm not sure if changing the dash for an underscore is the solution.

I don't even know if we still use this config, if changing this is even relevant.

**Comment by Conengmo** [comment]
`description-file` or `description_file` are both not supported keys: https://setuptools.pypa.io/en/latest/userguide/declarative_config.html. Instead we should use `long_description`. See this Stackoverflow answer: https://stackoverflow.com/questions/60084128/does-description-file-in-setup-cfg-section-metadata-have-any-effect.

I'll update the PR to use `long_description`. Also, `license_file` should be `license_files`.

**Comment by Conengmo** [comment]
Continued here: https://github.com/python-visualization/branca/pull/116

**Pull request closed without merging**
