### PR TITLE
Reversing color support for colorbrewer schemes

### PR DESCRIPTION
**Pull request by nanodan**
The way folium seems to create my choropleths is with the color gradients going the "wrong" direction.  This change simply allows for a "_r" at the end of the color code supplied to color_brewer() to allow for a reversal of the scheme.

### CODE REVIEW

**Comment by ocefpaf** [comment]
LGTM. Do you think you can add a simple test for that? (And probably the current behavior too :wink:)

**Comment by nanodan** [comment]
Added.

**Comment by nanodan** [comment]
All tests passed now - good to go.

**Comment by nanodan** [comment]
crap - shouldn't have pushed those commits to this branch, will roll that back

**Comment by nanodan** [comment]
Okay back to normal, good to merge.

**Comment by BibMartin** [comment]
It seems good to me also ; can you squash your commits, please ?

**Comment by BibMartin** [comment]
Great it's a merge. Thanks @nanodan

**Pull request merged**
