### PR TITLE
Add class to handle step colormaps

### PR DESCRIPTION
**Pull request by matsavage**
Repeat of the _LinearColormaps class for step color maps

### CODE REVIEW

**Comment by ocefpaf** [comment]
Thanks @matsavage!  @BibMartin can you take a look at this? I am not familiar with all the color stuff you created yet :grimacing: 

@matsavage meanwhile can you add:
- a changelog entry;
- a simple test;
- a notebook demonstrating the use of the class (optional) .

**Comment by matsavage** [comment]
I think I have this now, sorry about all the emails you must have gotten about me doing things wrong. New to all of this.

**Comment by ocefpaf** [comment]
> I think I have this now, sorry about all the emails you must have gotten about me doing things wrong. New to all of this.

No problem. Let us give @BibMartin some time to look at this, but he may be buried in the day job. But don't let us forget this PR, if no one answer for 1-2 weeks ping me again and I'll review this.

**Comment by BibMartin** [comment]
Sorry for being a bit late. This PR looks just perfect: thanks @matsavage !
Can you squash your commits so that we can merge it, please ?

**Comment by ocefpaf** [comment]
> Can you squash your commits so that we can merge it, please ?

We can use GitHub's squash and merge :smile: 

screenshot from 2017-10-10 08-09-23

**Comment by matsavage** [comment]
Great, thanks everyone 👍 

@ocefpaf phew, I found pictures of that while searching, but couldn't find it anywhere!

**Comment by ocefpaf** [comment]
@BibMartin already approved so I guess it is OK for me to merge. Thanks @matsavage for the PR and @BibMartin for the review!

I guess I need to work on a new release soon :grimacing:

**Comment by BibMartin** [comment]
> We can use GitHub's squash and merge :smile:

didn't know about this. I definitely spend too few time here :wink:

**Pull request merged**
