### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by ocefpaf**
Publish docs using GitHub Actions instead of Travis-CI.

### CODE REVIEW

**Comment by Conengmo** [comment]
@ocefpaf  could it be the Action that publishes the docs runs on all pull requests? 

https://github.com/python-visualization/branca/actions/workflows/deploy-docs.yml

https://github.com/python-visualization/branca/blob/main/.github/workflows/deploy-docs.yml#L4

**Comment by Conengmo** [comment]
Same for the Pypi Action, do we need that on all commits? I know at the bottom there's a check, but still, maybe wasteful? https://github.com/python-visualization/branca/blob/main/.github/workflows/pypi.yml

**Comment by ocefpaf** [comment]
I don't think it is wasteful b/c both runs pretty quickly. They do help ensure the tarball and docs are not broken by code changes.
If you feel strongly about it we can run only on deployment instead.

**Comment by Conengmo** [comment]
Alright, that sounds reasonable. Thanks for commenting on this :)

**Comment by ocefpaf** [comment]
BTW, if we do want to save resources, we can test Windows and macOS only for latest Python. That would reduce the testing matrix significantly and those OSes are usually the slower ones to spin up on GHA.

**Comment by martinfleis** [comment]
+1 on that.

**Pull request merged**
