### PR TITLE
Update the colormap HTML representation 

### PR DESCRIPTION
**Pull request by HaudinFlorence**
Update the colormap HTML representation to match the way it renders on Folium maps.
Here is a preview of the colormap used with Choropleth layer from ipyleaflet.

Screenshot from 2022-05-04 09-59-32

### CODE REVIEW

**Comment by martinRenou** [comment]
@ocefpaf it would be great if you could consider this PR for the next release :) We'd like to use branca more in ipyleaflet

**Comment by HaudinFlorence** [comment]
> @ocefpaf it would be great if you could consider this PR for the next release :) We'd like to use branca more in ipyleaflet
Screenshot from 2022-05-05 16-28-14-2

Here is another example of the use of Branca and the custom colormap in ipyleaflet

**Comment by HaudinFlorence** [comment]
@Conengmo @ocefpaf Another possible use of the customized Branca colormap proposed in this PR is with Heatmap layer. 
heatmap

**Comment by davidbrochart** [comment]
It looks like the maintainers are busy, we'd like to move forwards with this.
Is there any way we can help you @ocefpaf? Maybe you can give one of use commit rights?

**Comment by martinfleis** [comment]
Also happy to help with branca and folium maintenance if needed.

**Comment by HaudinFlorence** [comment]
Hello, is there any way of making things progress on this PR please ? Many thanks.

**Comment by Conengmo** [comment]
I had to check, because I normally don't use the `Colormap._repr_html_` method. It does look better this way! It would be nice to reuse more of the code/template we use in the 'normal' `render` function, but that shouldn't hold back this change.

- I added a docstring to the method.
- Changed the example notebook to not use ipyleaflet, since that's currently not a (dev) dependency for branca. It still shows the example fine.

I'll merge after the tests ran.

**Comment by ocefpaf** [comment]
> Also happy to help with branca and folium maintenance if needed.

I completely missed this PR and the comments here, sorry. BTW, I'd love to take on your offer here. Does that still stands?

**Comment by ocefpaf** [comment]
@martinfleis I'm assuming you are in for `branca` and `folium`, right?

@HaudinFlorence are you or others in your team interested too? Would that be only `branca` b/c it is now an ipyleaflet dependency?

**Comment by martinfleis** [comment]
> I'm assuming you are in for branca and folium, right?

Yup. Can't promise a ton of activity but some for sure.

**Comment by ocefpaf** [comment]
> Can't promise a ton of activity but some for sure.

I'm sure it will be more than what I have been offering these projects lately :-)

**Comment by HaudinFlorence** [comment]
> @HaudinFlorence are you or others in your team interested too? Would that be only `branca` b/c it is now an ipyleaflet dependency?

Thanks a lot for merging the PR @ocefpaf . We might indeed mainly contribute to branca to upstream features needed in ipyleaflet

**Comment by martinRenou** [comment]
Happy to help contribute too!

**Comment by ocefpaf** [comment]
You three should have access to branca and Martin also has access to folium. Thanks!

**Comment by HaudinFlorence** [comment]
> You three should have access to branca and Martin also has access to folium. Thanks!

@ocefpaf Can you please re regive me access to Branca. I left the organization by mistake. Thanks.

**Comment by el-gif** [comment]
Hello @HaudinFlorence, how do you know which colormap (viridis, plasma etc.) to use for the correct matching in your screenshots of the Heatmap and Velocity layers? Also, I am working with Shiny for Python to create a Webapp and ColormapControl doesn't seem to work in this constellation (ColormapControl created in the server function).

**Pull request merged**
