### PR TITLE
ReST README

### PR DESCRIPTION
**Pull request by ocefpaf**
The markdown version was not listed on `MANIFEST.in`, so I took this opportunity to add the `ReST` version to the manifest. That way the README is PyPI friendly and still renders well on GitHub.

### CODE REVIEW

**Comment by BibMartin** [comment]
Sorry @ocefpaf, I've been really busy these weeks.

Merge.

**Comment by ocefpaf** [comment]
I just submitted this. So that was very fast :wink:

**Comment by BibMartin** [comment]
Ok, sorry for other pending things... I'll try to have a look more often.

**Comment by ocefpaf** [comment]
@BibMartin this totally escaped me. We need a new release so I can package this in `conda`. Do I have access to the `PyPI`?  am creating a GitHub `v0.1.2` release, is that OK?

**Pull request merged**
